image: tmaier/docker-compose:latest

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

api_test:
  stage: test
  before_script:
    - apk update && apk add git
    - git clone https://gitlab.com/devscola/consensus-api.git
    - cd consensus-api
  script:
    - docker-compose -f docker-compose.ci.yml up --build -d
    - docker-compose -f docker-compose.ci.yml run api bundle exec rake test
    - docker-compose -f docker-compose.ci.yml down
  after_script:
    - cd ..

app_test:
  stage: test
  before_script:
    - apk update && apk add git
    - git clone https://gitlab.com/devscola/consensus.git
    - cd consensus
  script:
    - docker-compose -f docker-compose.yml up --build -d
    - docker-compose -f docker-compose.yml run consensus npm run build
    - docker-compose -f docker-compose.yml run consensus npm run test-all
    - docker-compose -f docker-compose.yml down
  after_script:
    - cd ..

build:
  stage: build
  script:
    - mkdir consensus17
    - cp -r consensus/public consensus17/
    - cp -r consensus-api/app.rb consensus17/
    - cp -r consensus-api/config.ru consensus17/
    - cp -r consensus-api/Gemfile consensus17/
    - cp -r consensus-api/Gemfile.lock consensus17/
    - cp -r consensus-api/images consensus17/
    - cp -r consensus-api/initializers consensus17/
    - cp -r consensus-api/system consensus17/
    - cp -r consensus-api/templates consensus17/
    - cp -r consensus-api/ testing/
    - echo "-----------------------------into-consensus17--------------------------"
    - cd consensus17
    - ls -la
    - cd ..
